name: Deploy JobHub

on:
  push:
    branches: [ main ]

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    - name: Build Docker Image
      run: docker build -t jobhub .

    - name: Run container (for testing only)
      run: docker run -d -p 3000:3000 jobhub
